<?php

declare(strict_types=1);

namespace DbToolsBundle\PackDeDE\Anonymizer;

use MakinaCorpus\DbToolsBundle\Anonymization\Anonymizer\AbstractMultipleColumnAnonymizer;
use MakinaCorpus\DbToolsBundle\Attribute\AsAnonymizer;

/**
 * Anonymized a complete address with a sample of 500 dumb german addresses.
 *
 * This anonymizer handle:
 *  - country: The country. For example, Deutschland.
 *  - locality: The locality in which the street address is,
 *    and which is in the region. For example, Nantes.
 *  - region: The region in which the locality is, and which is in the country.
 *    For example, Pays de la Loire or another appropriate first-level Administrative division.
 *  - postal_code: The postal code. For example, 44000.
 *  - street_address: The street address. For example, Hauptstraße 123.
 *  - secondary_address: Additional information (apartment, block)
 *
 * Sample from https://randommer.io/random-address
 */
#[AsAnonymizer(
    name: 'address',
    pack: 'de-de',
    description: <<<TXT
    Anonymize a mutlicolumn postal address.
    Map columns for each part with options ('country', 'locality', 'region', 'postal_code', 'street_address', 'secondary_address')
    TXT
)]
class AddressAnonymizer extends AbstractMultipleColumnAnonymizer
{
    /**
     * @inheritdoc
     */
    protected function getColumnNames(): array
    {
        return [
            'street_address',
            'secondary_address',
            'postal_code',
            'locality',
            'region',
            'country',
        ];
    }

    /**
     * @inheritdoc
     */
    protected function getSamples(): array
    {
        return [
            ["Hauptstraße 123", "Appartement 7", 45678, "Musterstadt", "Bayern", "Deutschland"],
            ["Bahnhofstraße 456", "Wohnung 9", 12345, "Beispielstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Lindenallee 789", "Appartement 2", 67890, "Musterort", "Hessen", "Deutschland"],
            ["Kirchplatz 321", "Zimmer 15", 54321, "Probestadt", "Niedersachsen", "Deutschland"],
            ["Bergweg 159", "Wohnung 4", 98765, "Testdorf", "Rheinland-Pfalz", "Deutschland"],
            ["Marktplatz 753", "Appartement 11", 24680, "Beispielheim", "Baden-Württemberg", "Deutschland"],
            ["Eichstraße 951", "Zimmer 6", 13579, "Musterburg", "Bayern", "Deutschland"],
            ["Dorfstraße 357", "Wohnung 14", 86420, "Probeort", "Sachsen", "Deutschland"],
            ["Lindenweg 753", "Appartement 3", 97531, "Teststadt", "Sachsen-Anhalt", "Deutschland"],
            ["Hauptplatz 159", "Zimmer 8", 64208, "Beispieldorf", "Thüringen", "Deutschland"],
            ["Bergstraße 951", "Wohnung 12", 86420, "Musterheim", "Brandenburg", "Deutschland"],
            ["Marktgasse 357", "Appartement 5", 97531, "Probeheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Eichplatz 753", "Zimmer 10", 64208, "Testburg", "Bremen", "Deutschland"],
            ["Dorfweg 159", "Wohnung 7", 86420, "Beispielort", "Hamburg", "Deutschland"],
            ["Lindenstraße 951", "Appartement 13", 97531, "Musterstadt", "Saarland", "Deutschland"],
            ["Hauptgasse 357", "Zimmer 2", 64208, "Probeheim", "Berlin", "Deutschland"],
            ["Bergplatz 753", "Wohnung 9", 86420, "Beispieldorf", "Nordrhein-Westfalen", "Deutschland"],
            ["Marktweg 159", "Appartement 6", 97531, "Musterburg", "Hessen", "Deutschland"],
            ["Eichweg 951", "Zimmer 14", 64208, "Teststadt", "Niedersachsen", "Deutschland"],
            ["Dorfgasse 357", "Wohnung 3", 86420, "Beispielort", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenplatz 753", "Appartement 11", 97531, "Musterheim", "Baden-Württemberg", "Deutschland"],
            ["Hauptstraße 123", "Wohnung 4", 12345, "Musterstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Lindenweg 456", "Appartement 9", 67890, "Beispielort", "Hessen", "Deutschland"],
            ["Kirchgasse 789", "Zimmer 2", 54321, "Probeheim", "Niedersachsen", "Deutschland"],
            ["Bergplatz 159", "Wohnung 11", 98765, "Testburg", "Rheinland-Pfalz", "Deutschland"],
            ["Marktstraße 753", "Appartement 6", 24680, "Musterheim", "Baden-Württemberg", "Deutschland"],
            ["Eichweg 951", "Zimmer 14", 13579, "Beispielstadt", "Bayern", "Deutschland"],
            ["Dorfgasse 357", "Wohnung 3", 86420, "Probeort", "Sachsen", "Deutschland"],
            ["Lindenallee 753", "Appartement 8", 97531, "Testdorf", "Sachsen-Anhalt", "Deutschland"],
            ["Hauptplatz 159", "Zimmer 12", 64208, "Musterburg", "Thüringen", "Deutschland"],
            ["Bergweg 951", "Wohnung 5", 86420, "Beispieldorf", "Brandenburg", "Deutschland"],
            ["Marktgasse 357", "Appartement 13", 97531, "Probeheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Eichstraße 753", "Zimmer 7", 64208, "Teststadt", "Bremen", "Deutschland"],
            ["Dorfplatz 159", "Wohnung 1", 86420, "Musterort", "Hamburg", "Deutschland"],
            ["Lindenweg 951", "Appartement 10", 97531, "Beispielheim", "Saarland", "Deutschland"],
            ["Hauptgasse 357", "Zimmer 15", 64208, "Probestadt", "Berlin", "Deutschland"],
            ["Bergallee 753", "Wohnung 4", 86420, "Testdorf", "Nordrhein-Westfalen", "Deutschland"],
            ["Marktplatz 159", "Appartement 11", 97531, "Musterheim", "Hessen", "Deutschland"],
            ["Eichgasse 951", "Zimmer 3", 64208, "Beispielort", "Niedersachsen", "Deutschland"],
            ["Dorfweg 357", "Wohnung 8", 86420, "Probeheim", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenstraße 753", "Appartement 14", 97531, "Testburg", "Baden-Württemberg", "Deutschland"],
            ["Hauptweg 159", "Zimmer 6", 64208, "Musterstadt", "Bayern", "Deutschland"],
            ["Bergplatz 951", "Wohnung 1", 86420, "Beispieldorf", "Sachsen", "Deutschland"],
            ["Marktgasse 357", "Appartement 12", 97531, "Probeort", "Sachsen-Anhalt", "Deutschland"],
            ["Eichstraße 753", "Zimmer 5", 64208, "Testdorf", "Thüringen", "Deutschland"],
            ["Dorfweg 159", "Wohnung 9", 86420, "Musterheim", "Brandenburg", "Deutschland"],
            ["Lindenallee 951", "Appartement 3", 97531, "Beispielheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Hauptplatz 357", "Zimmer 13", 64208, "Probestadt", "Bremen", "Deutschland"],
            ["Bahnhofweg 246", "Wohnung 7", 54321, "Musterstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Lindenplatz 789", "Appartement 11", 98765, "Beispielort", "Hessen", "Deutschland"],
            ["Kirchstraße 159", "Zimmer 4", 24680, "Probeheim", "Niedersachsen", "Deutschland"],
            ["Bergweg 753", "Wohnung 13", 13579, "Testburg", "Rheinland-Pfalz", "Deutschland"],
            ["Marktgasse 951", "Appartement 2", 86420, "Musterheim", "Baden-Württemberg", "Deutschland"],
            ["Eichplatz 357", "Zimmer 8", 97531, "Beispielstadt", "Bayern", "Deutschland"],
            ["Dorfstraße 753", "Wohnung 14", 64208, "Probeort", "Sachsen", "Deutschland"],
            ["Lindenweg 159", "Appartement 5", 86420, "Testdorf", "Sachsen-Anhalt", "Deutschland"],
            ["Hauptgasse 951", "Zimmer 11", 97531, "Musterburg", "Thüringen", "Deutschland"],
            ["Bergplatz 357", "Wohnung 3", 64208, "Beispieldorf", "Brandenburg", "Deutschland"],
            ["Marktstraße 753", "Appartement 9", 86420, "Probeheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Eichweg 159", "Zimmer 6", 97531, "Teststadt", "Bremen", "Deutschland"],
            ["Dorfplatz 951", "Wohnung 12", 64208, "Musterort", "Hamburg", "Deutschland"],
            ["Lindenallee 357", "Appartement 1", 86420, "Beispielheim", "Saarland", "Deutschland"],
            ["Hauptstraße 753", "Zimmer 7", 97531, "Probestadt", "Berlin", "Deutschland"],
            ["Bergweg 159", "Wohnung 10", 64208, "Testdorf", "Nordrhein-Westfalen", "Deutschland"],
            ["Marktgasse 951", "Appartement 4", 86420, "Musterheim", "Hessen", "Deutschland"],
            ["Eichplatz 357", "Zimmer 13", 97531, "Beispielort", "Niedersachsen", "Deutschland"],
            ["Dorfstraße 753", "Wohnung 2", 64208, "Probeheim", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenweg 159", "Appartement 8", 86420, "Testburg", "Baden-Württemberg", "Deutschland"],
            ["Hauptplatz 246", "Wohnung 11", 12345, "Beispielstadt", "Bayern", "Deutschland"],
            ["Lindenstraße 789", "Appartement 5", 67890, "Musterort", "Sachsen", "Deutschland"],
            ["Kirchweg 159", "Zimmer 14", 54321, "Probeheim", "Sachsen-Anhalt", "Deutschland"],
            ["Bergplatz 753", "Wohnung 3", 98765, "Testburg", "Thüringen", "Deutschland"],
            ["Marktstraße 951", "Appartement 8", 24680, "Musterheim", "Brandenburg", "Deutschland"],
            ["Eichgasse 357", "Zimmer 1", 13579, "Beispieldorf", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Dorfweg 753", "Wohnung 12", 86420, "Probeort", "Bremen", "Deutschland"],
            ["Lindenplatz 159", "Appartement 6", 97531, "Teststadt", "Hamburg", "Deutschland"],
            ["Hauptstraße 951", "Zimmer 9", 64208, "Musterstadt", "Saarland", "Deutschland"],
            ["Bergweg 357", "Wohnung 4", 86420, "Beispielheim", "Berlin", "Deutschland"],
            ["Marktgasse 753", "Appartement 13", 97531, "Probestadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichplatz 159", "Zimmer 2", 64208, "Testdorf", "Hessen", "Deutschland"],
            ["Dorfstraße 951", "Wohnung 7", 86420, "Musterort", "Niedersachsen", "Deutschland"],
            ["Lindenallee 357", "Appartement 10", 97531, "Beispieldorf", "Rheinland-Pfalz", "Deutschland"],
            ["Hauptgasse 753", "Zimmer 5", 64208, "Probeheim", "Baden-Württemberg", "Deutschland"],
            ["Bergplatz 159", "Wohnung 11", 86420, "Testburg", "Bayern", "Deutschland"],
            ["Marktweg 951", "Appartement 3", 97531, "Musterstadt", "Sachsen", "Deutschland"],
            ["Eichstraße 357", "Zimmer 14", 64208, "Beispielort", "Sachsen-Anhalt", "Deutschland"],
            ["Dorfplatz 753", "Wohnung 6", 86420, "Probeheim", "Thüringen", "Deutschland"],
            ["Lindenweg 159", "Appartement 12", 97531, "Testdorf", "Brandenburg", "Deutschland"],
            ["Bahnhofstraße 369", "Wohnung 8", 45678, "Musterstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Lindenplatz 852", "Appartement 2", 91011, "Beispielort", "Hessen", "Deutschland"],
            ["Kirchweg 741", "Zimmer 15", 23456, "Probeheim", "Niedersachsen", "Deutschland"],
            ["Bergstraße 963", "Wohnung 6", 78901, "Testburg", "Rheinland-Pfalz", "Deutschland"],
            ["Marktgasse 258", "Appartement 11", 34567, "Musterheim", "Baden-Württemberg", "Deutschland"],
            ["Eichplatz 147", "Zimmer 4", 92011, "Beispielstadt", "Bayern", "Deutschland"],
            ["Dorfweg 369", "Wohnung 13", 56789, "Probeort", "Sachsen", "Deutschland"],
            ["Lindenstraße 852", "Appartement 7", 23456, "Testdorf", "Sachsen-Anhalt", "Deutschland"],
            ["Hauptplatz 741", "Zimmer 10", 78901, "Musterburg", "Thüringen", "Deutschland"],
            ["Bergweg 963", "Wohnung 3", 34567, "Beispieldorf", "Brandenburg", "Deutschland"],
            ["Marktstraße 258", "Appartement 14", 92011, "Probeheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Eichgasse 147", "Zimmer 5", 56789, "Teststadt", "Bremen", "Deutschland"],
            ["Dorfplatz 369", "Wohnung 1", 23456, "Musterort", "Hamburg", "Deutschland"],
            ["Lindenallee 852", "Appartement 12", 78901, "Beispielheim", "Saarland", "Deutschland"],
            ["Hauptweg 741", "Zimmer 9", 34567, "Probestadt", "Berlin", "Deutschland"],
            ["Bergstraße 963", "Wohnung 6", 92011, "Testdorf", "Nordrhein-Westfalen", "Deutschland"],
            ["Marktgasse 258", "Appartement 3", 56789, "Musterheim", "Hessen", "Deutschland"],
            ["Eichplatz 147", "Zimmer 14", 23456, "Beispielort", "Niedersachsen", "Deutschland"],
            ["Dorfweg 369", "Wohnung 8", 78901, "Probeheim", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenstraße 852", "Appartement 11", 34567, "Testburg", "Baden-Württemberg", "Deutschland"],
            ["Bahnhofplatz 159", "Wohnung 4", 12345, "Musterstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Lindenweg 753", "Appartement 11", 67890, "Beispielort", "Hessen", "Deutschland"],
            ["Kirchstraße 951", "Zimmer 7", 54321, "Probeheim", "Niedersachsen", "Deutschland"],
            ["Bergweg 357", "Wohnung 13", 98765, "Testburg", "Rheinland-Pfalz", "Deutschland"],
            ["Marktplatz 159", "Appartement 2", 24680, "Musterheim", "Baden-Württemberg", "Deutschland"],
            ["Eichgasse 753", "Zimmer 9", 13579, "Beispielstadt", "Bayern", "Deutschland"],
            ["Dorfstraße 951", "Wohnung 5", 86420, "Probeort", "Sachsen", "Deutschland"],
            ["Lindenallee 357", "Appartement 14", 97531, "Testdorf", "Sachsen-Anhalt", "Deutschland"],
            ["Hauptweg 159", "Zimmer 3", 64208, "Musterburg", "Thüringen", "Deutschland"],
            ["Bergplatz 753", "Wohnung 10", 86420, "Beispieldorf", "Brandenburg", "Deutschland"],
            ["Marktgasse 951", "Appartement 6", 97531, "Probeheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Eichstraße 357", "Zimmer 12", 64208, "Teststadt", "Bremen", "Deutschland"],
            ["Dorfplatz 159", "Wohnung 1", 86420, "Musterort", "Hamburg", "Deutschland"],
            ["Lindenweg 753", "Appartement 8", 97531, "Beispielheim", "Saarland", "Deutschland"],
            ["Hauptgasse 951", "Zimmer 15", 64208, "Probestadt", "Berlin", "Deutschland"],
            ["Bergstraße 357", "Wohnung 4", 86420, "Testdorf", "Nordrhein-Westfalen", "Deutschland"],
            ["Marktplatz 159", "Appartement 11", 97531, "Musterheim", "Hessen", "Deutschland"],
            ["Eichweg 753", "Zimmer 3", 64208, "Beispielort", "Niedersachsen", "Deutschland"],
            ["Dorfstraße 951", "Wohnung 8", 86420, "Probeheim", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenallee 357", "Appartement 14", 97531, "Testburg", "Baden-Württemberg", "Deutschland"],
            ["Hauptplatz 159", "Zimmer 6", 64208, "Musterstadt", "Bayern", "Deutschland"],
            ["Bergweg 753", "Wohnung 1", 86420, "Beispieldorf", "Sachsen", "Deutschland"],
            ["Marktgasse 951", "Appartement 12", 97531, "Probeort", "Sachsen-Anhalt", "Deutschland"],
            ["Eichstraße 357", "Zimmer 5", 64208, "Testdorf", "Thüringen", "Deutschland"],
            ["Dorfplatz 159", "Wohnung 9", 86420, "Musterheim", "Brandenburg", "Deutschland"],
            ["Lindenweg 753", "Appartement 3", 97531, "Beispielheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Hauptgasse 951", "Zimmer 13", 64208, "Probestadt", "Bremen", "Deutschland"],
            ["Bahnhofplatz 246", "Wohnung 7", 12345, "Musterstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Lindenweg 852", "Appartement 11", 67890, "Beispielort", "Hessen", "Deutschland"],
            ["Kirchstraße 741", "Zimmer 4", 54321, "Probeheim", "Niedersachsen", "Deutschland"],
            ["Bergweg 963", "Wohnung 13", 98765, "Testburg", "Rheinland-Pfalz", "Deutschland"],
            ["Marktgasse 258", "Appartement 2", 24680, "Musterheim", "Baden-Württemberg", "Deutschland"],
            ["Eichplatz 147", "Zimmer 8", 13579, "Beispielstadt", "Bayern", "Deutschland"],
            ["Dorfstraße 369", "Wohnung 14", 86420, "Probeort", "Sachsen", "Deutschland"],
            ["Lindenallee 852", "Appartement 5", 97531, "Testdorf", "Sachsen-Anhalt", "Deutschland"],
            ["Hauptplatz 741", "Zimmer 11", 64208, "Musterburg", "Thüringen", "Deutschland"],
            ["Bergstraße 963", "Wohnung 3", 86420, "Beispieldorf", "Brandenburg", "Deutschland"],
            ["Marktweg 258", "Appartement 14", 97531, "Probeheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Eichgasse 147", "Zimmer 6", 64208, "Teststadt", "Bremen", "Deutschland"],
            ["Dorfplatz 369", "Wohnung 1", 86420, "Musterort", "Hamburg", "Deutschland"],
            ["Lindenstraße 852", "Appartement 12", 97531, "Beispielheim", "Saarland", "Deutschland"],
            ["Hauptgasse 741", "Zimmer 9", 64208, "Probestadt", "Berlin", "Deutschland"],
            ["Bergweg 963", "Wohnung 6", 86420, "Testdorf", "Nordrhein-Westfalen", "Deutschland"],
            ["Marktstraße 258", "Appartement 3", 97531, "Musterheim", "Hessen", "Deutschland"],
            ["Eichplatz 147", "Zimmer 14", 64208, "Beispielort", "Niedersachsen", "Deutschland"],
            ["Dorfweg 369", "Wohnung 8", 86420, "Probeheim", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenallee 852", "Appartement 11", 97531, "Testburg", "Baden-Württemberg", "Deutschland"],
            ["Bahnhofstraße 159", "Wohnung 4", 45678, "Musterstadt", "Bayern", "Deutschland"],
            ["Lindenplatz 753", "Appartement 11", 91011, "Beispielort", "Sachsen", "Deutschland"],
            ["Kirchweg 951", "Zimmer 7", 23456, "Probeheim", "Sachsen-Anhalt", "Deutschland"],
            ["Bergstraße 357", "Wohnung 13", 78901, "Testburg", "Thüringen", "Deutschland"],
            ["Marktgasse 159", "Appartement 2", 34567, "Musterheim", "Brandenburg", "Deutschland"],
            ["Eichweg 753", "Zimmer 9", 92011, "Beispielstadt", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Dorfplatz 951", "Wohnung 5", 56789, "Probeort", "Bremen", "Deutschland"],
            ["Hauptstraße 369", "Wohnung 8", 12345, "Musterstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Lindenweg 852", "Appartement 2", 67890, "Beispielort", "Hessen", "Deutschland"],
            ["Kirchplatz 741", "Zimmer 15", 54321, "Probeheim", "Niedersachsen", "Deutschland"],
            ["Bergweg 963", "Wohnung 6", 98765, "Testburg", "Rheinland-Pfalz", "Deutschland"],
            ["Marktstraße 258", "Appartement 11", 24680, "Musterheim", "Baden-Württemberg", "Deutschland"],
            ["Eichgasse 147", "Zimmer 4", 13579, "Beispielstadt", "Bayern", "Deutschland"],
            ["Dorfplatz 369", "Wohnung 13", 86420, "Probeort", "Sachsen", "Deutschland"],
            ["Lindenallee 852", "Appartement 7", 97531, "Testdorf", "Sachsen-Anhalt", "Deutschland"],
            ["Hauptweg 741", "Zimmer 10", 64208, "Musterburg", "Thüringen", "Deutschland"],
            ["Bergstraße 963", "Wohnung 3", 86420, "Beispieldorf", "Brandenburg", "Deutschland"],
            ["Marktgasse 258", "Appartement 14", 97531, "Probeheim", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Eichplatz 147", "Zimmer 5", 64208, "Teststadt", "Bremen", "Deutschland"],
            ["Dorfweg 369", "Wohnung 1", 86420, "Musterort", "Hamburg", "Deutschland"],
            ["Lindenstraße 852", "Appartement 12", 97531, "Beispielheim", "Saarland", "Deutschland"],
            ["Hauptgasse 741", "Zimmer 9", 64208, "Probestadt", "Berlin", "Deutschland"],
            ["Bergweg 963", "Wohnung 6", 86420, "Testdorf", "Nordrhein-Westfalen", "Deutschland"],
            ["Marktstraße 258", "Appartement 3", 97531, "Musterheim", "Hessen", "Deutschland"],
            ["Eichgasse 147", "Zimmer 14", 64208, "Beispielort", "Niedersachsen", "Deutschland"],
            ["Dorfplatz 369", "Wohnung 8", 86420, "Probeheim", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenallee 852", "Appartement 11", 97531, "Testburg", "Baden-Württemberg", "Deutschland"],
            ["Bahnhofstraße 159", "Wohnung 4", 45678, "Musterstadt", "Bayern", "Deutschland"],
            ["Lindenweg 753", "Appartement 11", 91011, "Beispielort", "Sachsen", "Deutschland"],
            ["Kirchstraße 951", "Zimmer 7", 23456, "Probeheim", "Sachsen-Anhalt", "Deutschland"],
            ["Bergplatz 357", "Wohnung 13", 78901, "Testburg", "Thüringen", "Deutschland"],
            ["Marktgasse 159", "Appartement 2", 34567, "Musterheim", "Brandenburg", "Deutschland"],
            ["Eichweg 753", "Zimmer 9", 92011, "Beispielstadt", "Mecklenburg-Vorpommern", "Deutschland"],
            ["Dorfstraße 951", "Wohnung 5", 56789, "Probeort", "Bremen", "Deutschland"],
            ["Bahnhofstraße 124", "Appartement 3", 54321, "Kleinstadt", "Bayern", "Deutschland"],
            ["Lindenallee 78", "Wohnung 11", 67890, "Mittelstadt", "Hessen", "Deutschland"],
            ["Bergstraße 45", "Appartement 6", 24680, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Eichendorffweg 901", "Wohnung 2", 13579, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Marktplatz 567", "Appartement 9", 86420, "Altstadt", "Sachsen", "Deutschland"],
            ["Tannenweg 234", "Wohnung 5", 97531, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Kirchstraße 890", "Appartement 7", 65432, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Rosenweg 456", "Wohnung 1", 24135, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Hauptplatz 789", "Appartement 4", 86753, "Großstadt", "Bayern", "Deutschland"],
            ["Fichtenallee 321", "Wohnung 10", 13246, "Dorfstadt", "Hessen", "Deutschland"],
            ["Marktgasse 654", "Appartement 8", 97864, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Lindenstraße 987", "Wohnung 3", 24579, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Kirchweg 246", "Appartement 5", 86913, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Rosenplatz 579", "Wohnung 2", 13579, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Hauptgasse 864", "Appartement 9", 97531, "Großstadt", "Thüringen", "Deutschland"],
            ["Fichtenweg 135", "Wohnung 6", 24680, "Dorfstadt", "Baden-Württemberg", "Deutschland"],
            ["Marktstraße 798", "Appartement 1", 86420, "Altstadt", "Bayern", "Deutschland"],
            ["Lindenplatz 246", "Wohnung 7", 13246, "Neustadt", "Hessen", "Deutschland"],
            ["Kirchgasse 579", "Appartement 4", 97864, "Kleinstadt", "Niedersachsen", "Deutschland"],
            ["Rosenallee 864", "Wohnung 10", 24135, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Hauptweg 135", "Appartement 3", 86913, "Großstadt", "Sachsen", "Deutschland"],
            ["Fichtenstraße 798", "Wohnung 8", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Marktplatz 246", "Appartement 5", 97531, "Altstadt", "Thüringen", "Deutschland"],
            ["Lindenweg 579", "Wohnung 1", 24680, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Kirchallee 864", "Appartement 7", 86420, "Kleinstadt", "Bayern", "Deutschland"],
            ["Rosenstraße 135", "Wohnung 4", 13246, "Mittelstadt", "Hessen", "Deutschland"],
            ["Hauptgasse 798", "Appartement 10", 97864, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Birkenweg 321", "Appartement 2", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichenstraße 654", "Wohnung 8", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenallee 987", "Appartement 5", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Kiefernweg 159", "Wohnung 3", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenplatz 753", "Appartement 9", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Eschenstraße 951", "Wohnung 6", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Föhrenweg 357", "Appartement 1", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Lärchengasse 852", "Wohnung 7", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Tannengasse 456", "Appartement 4", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Birkengasse 159", "Wohnung 10", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Eichenweg 753", "Appartement 2", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Tannenplatz 951", "Wohnung 8", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Kiefernstraße 357", "Appartement 5", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Buchenallee 852", "Wohnung 1", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Eschenweg 456", "Appartement 7", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Föhrengasse 159", "Wohnung 4", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Lärchengasse 753", "Appartement 10", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Tannengasse 951", "Wohnung 3", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Birkengasse 357", "Appartement 6", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Eichenweg 852", "Wohnung 9", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Tannenplatz 456", "Appartement 1", 86913, "Großstadt", "Thüringen", "Deutschland"],
            ["Kiefernstraße 159", "Wohnung 7", 13579, "Dorfstadt", "Baden-Württemberg", "Deutschland"],
            ["Buchenallee 753", "Appartement 4", 97531, "Altstadt", "Bayern", "Deutschland"],
            ["Eschenweg 951", "Wohnung 10", 24680, "Neustadt", "Hessen", "Deutschland"],
            ["Föhrengasse 357", "Appartement 2", 86420, "Kleinstadt", "Niedersachsen", "Deutschland"],
            ["Lindenweg 642", "Appartement 6", 54321, "Mittelstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Kirchplatz 975", "Wohnung 3", 67890, "Großstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Rosenstraße 318", "Appartement 8", 24680, "Dorfstadt", "Sachsen", "Deutschland"],
            ["Hauptgasse 451", "Wohnung 1", 13579, "Altstadt", "Schleswig-Holstein", "Deutschland"],
            ["Fichtenweg 786", "Appartement 5", 86420, "Neustadt", "Thüringen", "Deutschland"],
            ["Marktplatz 209", "Wohnung 9", 97531, "Kleinstadt", "Baden-Württemberg", "Deutschland"],
            ["Lindenallee 642", "Appartement 2", 65432, "Mittelstadt", "Bayern", "Deutschland"],
            ["Kirchweg 975", "Wohnung 7", 24135, "Großstadt", "Hessen", "Deutschland"],
            ["Rosenplatz 318", "Appartement 4", 86753, "Dorfstadt", "Niedersachsen", "Deutschland"],
            ["Hauptstraße 451", "Wohnung 10", 13246, "Altstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Fichtenallee 786", "Appartement 1", 97864, "Neustadt", "Sachsen", "Deutschland"],
            ["Marktgasse 209", "Wohnung 6", 24579, "Kleinstadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenweg 642", "Appartement 3", 86913, "Mittelstadt", "Thüringen", "Deutschland"],
            ["Kirchplatz 975", "Wohnung 8", 13579, "Großstadt", "Baden-Württemberg", "Deutschland"],
            ["Rosenstraße 318", "Appartement 5", 97531, "Dorfstadt", "Bayern", "Deutschland"],
            ["Eichenweg 123", "Appartement 7", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Tannenstraße 456", "Wohnung 2", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Kiefernplatz 789", "Appartement 9", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Buchenallee 159", "Wohnung 4", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Eschenweg 753", "Appartement 6", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Föhrenstraße 951", "Wohnung 1", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Lärchengasse 357", "Appartement 8", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Tannengasse 852", "Wohnung 3", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Birkengasse 456", "Appartement 10", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Eichenweg 159", "Wohnung 5", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenplatz 753", "Appartement 2", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Kiefernstraße 951", "Wohnung 7", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenallee 357", "Appartement 4", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Eschenweg 852", "Wohnung 9", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Föhrengasse 456", "Appartement 1", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Lärchengasse 159", "Wohnung 6", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Tannengasse 753", "Appartement 3", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Birkengasse 951", "Wohnung 10", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Eichenweg 357", "Appartement 5", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Tannenplatz 852", "Wohnung 2", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Kiefernstraße 456", "Appartement 7", 86913, "Großstadt", "Thüringen", "Deutschland"],
            ["Buchenallee 159", "Wohnung 4", 13579, "Dorfstadt", "Baden-Württemberg", "Deutschland"],
            ["Eschenweg 753", "Appartement 9", 97531, "Altstadt", "Bayern", "Deutschland"],
            ["Föhrengasse 951", "Wohnung 1", 24680, "Neustadt", "Hessen", "Deutschland"],
            ["Lärchengasse 357", "Appartement 6", 86420, "Kleinstadt", "Niedersachsen", "Deutschland"],
            ["Tannengasse 852", "Wohnung 3", 13246, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Birkenstraße 246", "Appartement 5", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichenplatz 579", "Wohnung 1", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenweg 864", "Appartement 7", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Kiefernallee 135", "Wohnung 3", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenstraße 798", "Appartement 9", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Eschenplatz 246", "Wohnung 6", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Föhrenweg 579", "Appartement 2", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Lärchengasse 864", "Wohnung 8", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Tannengasse 135", "Appartement 4", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Birkengasse 798", "Wohnung 10", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Eichenweg 246", "Appartement 1", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Tannenplatz 579", "Wohnung 7", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Kiefernstraße 864", "Appartement 3", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Buchenallee 135", "Wohnung 9", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Eschenplatz 798", "Appartement 5", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Föhrenweg 246", "Wohnung 2", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Lärchengasse 579", "Appartement 8", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Tannengasse 864", "Wohnung 4", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Birkengasse 135", "Appartement 10", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Eichenweg 798", "Wohnung 6", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Tannenplatz 246", "Appartement 1", 86913, "Großstadt", "Thüringen", "Deutschland"],
            ["Kiefernstraße 579", "Wohnung 7", 13579, "Dorfstadt", "Baden-Württemberg", "Deutschland"],
            ["Buchenallee 864", "Appartement 3", 97531, "Altstadt", "Bayern", "Deutschland"],
            ["Eschenplatz 135", "Wohnung 9", 24680, "Neustadt", "Hessen", "Deutschland"],
            ["Föhrenweg 798", "Appartement 5", 86420, "Kleinstadt", "Niedersachsen", "Deutschland"],
            ["Lärchengasse 246", "Wohnung 2", 13246, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenstraße 321", "Appartement 6", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Kirchweg 654", "Wohnung 2", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Rosenplatz 987", "Appartement 8", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Hauptgasse 159", "Wohnung 4", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Fichtenallee 753", "Appartement 10", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Marktstraße 951", "Wohnung 1", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Lindenweg 357", "Appartement 7", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Kirchplatz 852", "Wohnung 3", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Rosenstraße 456", "Appartement 9", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Hauptallee 159", "Wohnung 5", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Fichtenweg 753", "Appartement 2", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Marktgasse 951", "Wohnung 8", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenstraße 357", "Appartement 4", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Kirchweg 852", "Wohnung 10", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Rosenplatz 456", "Appartement 1", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Hauptgasse 159", "Wohnung 6", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Fichtenallee 753", "Appartement 3", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Marktstraße 951", "Wohnung 9", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenweg 357", "Appartement 5", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Kirchplatz 852", "Wohnung 2", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Rosenstraße 456", "Appartement 7", 86913, "Großstadt", "Thüringen", "Deutschland"],
            ["Hauptallee 159", "Wohnung 4", 13579, "Dorfstadt", "Baden-Württemberg", "Deutschland"],
            ["Fichtenweg 753", "Appartement 10", 97531, "Altstadt", "Bayern", "Deutschland"],
            ["Marktgasse 951", "Wohnung 1", 24680, "Neustadt", "Hessen", "Deutschland"],
            ["Lindenstraße 357", "Appartement 6", 86420, "Kleinstadt", "Niedersachsen", "Deutschland"],
            ["Kirchweg 852", "Wohnung 3", 13246, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Rosenplatz 456", "Appartement 8", 97864, "Großstadt", "Sachsen", "Deutschland"],
            ["Birkenplatz 642", "Appartement 4", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichenstraße 975", "Wohnung 9", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenweg 318", "Appartement 2", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Kiefernallee 451", "Wohnung 7", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenplatz 786", "Appartement 3", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Eschenstraße 209", "Wohnung 8", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Föhrenweg 642", "Appartement 5", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Lärchengasse 975", "Wohnung 1", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Tannengasse 318", "Appartement 6", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Birkengasse 451", "Wohnung 10", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Eichenweg 786", "Appartement 3", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Tannenplatz 209", "Wohnung 8", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Kiefernstraße 642", "Appartement 5", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Buchenallee 975", "Wohnung 1", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Eschenweg 318", "Appartement 6", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Föhrenstraße 451", "Wohnung 2", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Lärchengasse 786", "Appartement 7", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Tannengasse 209", "Wohnung 4", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Birkengasse 642", "Appartement 9", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Eichenweg 975", "Wohnung 2", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Tannenplatz 318", "Appartement 7", 86913, "Großstadt", "Thüringen", "Deutschland"],
            ["Kiefernstraße 451", "Wohnung 4", 13579, "Dorfstadt", "Baden-Württemberg", "Deutschland"],
            ["Buchenallee 786", "Appartement 9", 97531, "Altstadt", "Bayern", "Deutschland"],
            ["Eschenweg 209", "Wohnung 2", 24680, "Neustadt", "Hessen", "Deutschland"],
            ["Föhrenstraße 642", "Appartement 7", 86420, "Kleinstadt", "Niedersachsen", "Deutschland"],
            ["Lärchengasse 975", "Wohnung 4", 13246, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenplatz 753", "Appartement 6", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Kirchstraße 951", "Wohnung 2", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Rosenweg 357", "Appartement 8", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Hauptplatz 852", "Wohnung 4", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Fichtenallee 456", "Appartement 10", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Marktgasse 159", "Wohnung 1", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Lindenstraße 753", "Appartement 7", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Kirchweg 951", "Wohnung 3", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Rosenplatz 357", "Appartement 9", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Hauptgasse 852", "Wohnung 5", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Fichtenweg 456", "Appartement 2", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Marktstraße 159", "Wohnung 8", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenplatz 753", "Appartement 4", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Kirchstraße 951", "Wohnung 10", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Rosenweg 357", "Appartement 1", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Birkenweg 642", "Appartement 5", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichenstraße 975", "Wohnung 1", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenplatz 318", "Appartement 7", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Kiefernallee 451", "Wohnung 3", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenweg 786", "Appartement 9", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Eschenstraße 209", "Wohnung 6", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Föhrenplatz 642", "Appartement 2", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Lärchengasse 975", "Wohnung 8", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Tannengasse 318", "Appartement 4", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Birkengasse 451", "Wohnung 10", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Eichenweg 786", "Appartement 1", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Tannenplatz 209", "Wohnung 7", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Kiefernstraße 642", "Appartement 3", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Buchenallee 975", "Wohnung 9", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Eschenweg 318", "Appartement 5", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Föhrenstraße 451", "Wohnung 1", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Lärchengasse 786", "Appartement 6", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Tannengasse 209", "Wohnung 2", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Birkengasse 642", "Appartement 8", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Eichenweg 975", "Wohnung 4", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenstraße 123", "Appartement 7", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Kirchweg 456", "Wohnung 2", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Rosenplatz 789", "Appartement 8", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Hauptgasse 159", "Wohnung 4", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Fichtenallee 753", "Appartement 10", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Marktstraße 951", "Wohnung 1", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Lindenweg 357", "Appartement 6", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Kirchplatz 852", "Wohnung 3", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Rosenstraße 456", "Appartement 9", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Hauptallee 159", "Wohnung 5", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Fichtenweg 753", "Appartement 2", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Marktgasse 951", "Wohnung 8", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenstraße 357", "Appartement 4", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Kirchweg 852", "Wohnung 10", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Rosenplatz 456", "Appartement 1", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Hauptgasse 159", "Wohnung 6", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Fichtenallee 753", "Appartement 3", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Marktstraße 951", "Wohnung 9", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenweg 357", "Appartement 5", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Kirchplatz 852", "Wohnung 2", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Birkenstraße 642", "Appartement 6", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichenplatz 975", "Wohnung 2", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenweg 318", "Appartement 8", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Kiefernallee 451", "Wohnung 4", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenstraße 786", "Appartement 10", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Eschenplatz 209", "Wohnung 1", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Föhrenweg 642", "Appartement 7", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Lärchengasse 975", "Wohnung 3", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Tannengasse 318", "Appartement 9", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Birkengasse 451", "Wohnung 5", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Eichenweg 786", "Appartement 2", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Tannenplatz 209", "Wohnung 8", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Kiefernstraße 642", "Appartement 4", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Buchenallee 975", "Wohnung 10", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Eschenweg 318", "Appartement 1", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Föhrenstraße 451", "Wohnung 6", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Lärchengasse 786", "Appartement 3", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Tannengasse 209", "Wohnung 9", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Birkengasse 642", "Appartement 5", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Eichenweg 975", "Wohnung 1", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenplatz 123", "Appartement 6", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Kirchstraße 456", "Wohnung 2", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Rosenweg 789", "Appartement 8", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Hauptgasse 159", "Wohnung 4", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Fichtenallee 753", "Appartement 10", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Marktstraße 951", "Wohnung 1", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Lindenweg 357", "Appartement 7", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Kirchplatz 852", "Wohnung 3", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Rosenstraße 456", "Appartement 9", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Hauptallee 159", "Wohnung 5", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Fichtenweg 753", "Appartement 2", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Marktgasse 951", "Wohnung 8", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenstraße 357", "Appartement 4", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Kirchweg 852", "Wohnung 10", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Rosenplatz 456", "Appartement 1", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Hauptgasse 159", "Wohnung 6", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Fichtenallee 753", "Appartement 3", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Marktstraße 951", "Wohnung 9", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenweg 357", "Appartement 5", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Kirchplatz 852", "Wohnung 2", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Birkenallee 642", "Appartement 7", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichenstraße 975", "Wohnung 3", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenplatz 318", "Appartement 9", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Kiefernweg 451", "Wohnung 5", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenallee 786", "Appartement 1", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Eschenplatz 209", "Wohnung 6", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Föhrenstraße 642", "Appartement 3", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Lärchengasse 975", "Wohnung 9", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Tannengasse 318", "Appartement 5", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Birkengasse 451", "Wohnung 2", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Eichenweg 786", "Appartement 7", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Tannenplatz 209", "Wohnung 4", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Kiefernstraße 642", "Appartement 10", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Buchenallee 975", "Wohnung 6", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Eschenweg 318", "Appartement 3", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Föhrenstraße 451", "Wohnung 8", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Lärchengasse 786", "Appartement 1", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Tannengasse 209", "Wohnung 5", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Birkengasse 642", "Appartement 2", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Eichenweg 975", "Wohnung 7", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenstraße 246", "Appartement 5", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Kirchweg 579", "Wohnung 1", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Rosenplatz 864", "Appartement 7", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Hauptgasse 135", "Wohnung 3", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Fichtenallee 798", "Appartement 9", 86420, "Altstadt", "Thüringen", "Deutschland"],
            ["Marktstraße 246", "Wohnung 6", 97531, "Neustadt", "Baden-Württemberg", "Deutschland"],
            ["Lindenweg 579", "Appartement 2", 65432, "Kleinstadt", "Bayern", "Deutschland"],
            ["Kirchplatz 864", "Wohnung 8", 24135, "Mittelstadt", "Hessen", "Deutschland"],
            ["Rosenstraße 135", "Appartement 4", 86753, "Großstadt", "Niedersachsen", "Deutschland"],
            ["Hauptallee 798", "Wohnung 10", 13246, "Dorfstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Fichtenweg 246", "Appartement 1", 97864, "Altstadt", "Sachsen", "Deutschland"],
            ["Marktgasse 579", "Wohnung 7", 24579, "Neustadt", "Schleswig-Holstein", "Deutschland"],
            ["Lindenstraße 864", "Appartement 3", 86913, "Kleinstadt", "Thüringen", "Deutschland"],
            ["Kirchweg 135", "Wohnung 9", 13579, "Mittelstadt", "Baden-Württemberg", "Deutschland"],
            ["Rosenplatz 798", "Appartement 5", 97531, "Großstadt", "Bayern", "Deutschland"],
            ["Hauptgasse 246", "Wohnung 2", 24680, "Dorfstadt", "Hessen", "Deutschland"],
            ["Fichtenallee 579", "Appartement 8", 86420, "Altstadt", "Niedersachsen", "Deutschland"],
            ["Marktstraße 864", "Wohnung 4", 13246, "Neustadt", "Rheinland-Pfalz", "Deutschland"],
            ["Lindenweg 135", "Appartement 10", 97864, "Kleinstadt", "Sachsen", "Deutschland"],
            ["Kirchplatz 798", "Wohnung 6", 24135, "Mittelstadt", "Schleswig-Holstein", "Deutschland"],
            ["Birkenstraße 951", "Appartement 4", 54321, "Kleinstadt", "Nordrhein-Westfalen", "Deutschland"],
            ["Eichenplatz 357", "Wohnung 9", 67890, "Mittelstadt", "Rheinland-Pfalz", "Deutschland"],
            ["Tannenweg 852", "Appartement 6", 24680, "Großstadt", "Sachsen", "Deutschland"],
            ["Kiefernallee 456", "Wohnung 2", 13579, "Dorfstadt", "Schleswig-Holstein", "Deutschland"],
            ["Buchenstraße 159", "Appartement 8", 86420, "Altstadt", "Thüringen", "Deutschland"],

        ];
    }
}
